version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: course_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courses_db
      MYSQL_USER: zeyad
      MYSQL_PASSWORD: backend123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

